---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: validate
    image: rancher/dapper:v0.6.0
    commands:
    - dapper ci
    volumes:
    - name: docker
      path: /var/run/docker.sock

  - name: upload
    pull: default
    image: plugins/gcs
    settings:
      acl:
      - allUsers:READER
      cache_control: "public,no-cache,proxy-revalidate"
      source: data
      target: releases.rancher.com/kontainer-driver-metadata/${DRONE_BRANCH}
      token:
        from_secret: google_auth_key
    when:
      event:
      - push
    depends_on:
    - validate


  - name: dispatch
    image: curlimages/curl:7.81.0
    user: root
    environment:
      PAT_USERNAME:
        from_secret: pat_username
      PAT_TOKEN:
        from_secret: github_token
    commands:
    - apk -U --no-cache add bash
    - scripts/dispatch
    when:
      event:
      - push
    depends_on:
    - upload

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: fossa

steps:
- name: fossa
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
  when:
    instance:
      - drone-publish.rancher.io

