ARG RANCHER_VERSION=v2.14-head

FROM rancher/rancher:$RANCHER_VERSION AS rancher

FROM registry.suse.com/bci/golang:1.25

# --- Tool installations (most expensive, no dependency on rancher content) ---
ARG TARGETARCH=amd64
ENV ARCH=${TARGETARCH}
# renovate: datasource=github-digest depName=golangci/golangci-lint digestVersion=v1.64.8
ENV GOLANGCI_LINT_REF=8b37f14162043f908949f1b363d061dc9ba713c0
# renovate: datasource=github-digest depName=golang/tools digestVersion=v0.43.0
ENV GOIMPORTS_REF=24a8e95f9d7ae2696f66314da5e50c0d98ccaa90

RUN zypper -n install git docker vim less file curl wget jq awk ruby && rpm -e --nodeps --noscripts containerd
RUN go install golang.org/x/tools/cmd/goimports@${GOIMPORTS_REF}
RUN if [[ "${ARCH}" == "amd64" ]]; then \
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_REF}; \
        # renovate: datasource=github-release-attachments depName=rancher/wharfie
        WHARFIE_VERSION=v0.6.1 && \
        # renovate: datasource=github-release-attachments depName=rancher/wharfie digestVersion=v0.6.1
        WHARFIE_SUM=7be7e1640f87389a8818916fb9e310ddb2f3b26f41193bd783f0086f97f0d206 && \
        curl -sL "https://github.com/rancher/wharfie/releases/download/${WHARFIE_VERSION}/wharfie-amd64" -o /bin/wharfie && \
        echo "${WHARFIE_SUM}  /bin/wharfie" | sha256sum -c - && \
        chmod +x /bin/wharfie; \
        # renovate: datasource=github-release-attachments depName=regclient/regclient
        REGSYNC_VERSION=v0.9.0 && \
        # renovate: datasource=github-release-attachments depName=regclient/regclient digestVersion=v0.9.0
        REGSYNC_SUM=fe8068cfe2fbd81d607608aa627b001311d191be32b8d8e1943fe68c84794522 && \
        curl -sL "https://github.com/regclient/regclient/releases/download/${REGSYNC_VERSION}/regsync-linux-amd64" -o /bin/regsync && \
        echo "${REGSYNC_SUM}  /bin/regsync" | sha256sum -c - && \
        chmod +x /bin/regsync; \
    fi

# renovate: datasource=github-release-attachments depName=mikefarah/yq
ENV YQ_VERSION=v4.52.5
# renovate: datasource=github-release-attachments depName=mikefarah/yq digestVersion=v4.52.5
ENV YQ_SUM_amd64=c529c33e6b545d95e39445c37f673e31ca110c3ca9310b47ccea78f9190b061e
# renovate: datasource=github-release-attachments depName=mikefarah/yq digestVersion=v4.52.5
ENV YQ_SUM_arm64=33cf72426fc5f5e7d9b99801a58d34c6fa7e4426dad594569fb972dde5891109
ENV YQ_SUM="YQ_SUM_${ARCH}"
RUN wget -q "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${ARCH}.tar.gz" -O /tmp/yq.tar.gz && \
    echo "${!YQ_SUM}  /tmp/yq.tar.gz" | sha256sum -c - && \
    tar xzf /tmp/yq.tar.gz -C /tmp && \
    mv /tmp/yq_linux_${ARCH} /usr/bin/yq && \
    rm /tmp/yq.tar.gz

# --- K3s binaries (pinned tag, stable cache key) ---
COPY --from=rancher/k3s:v1.36.2-k3s1 \
    /bin/blkid \
    /bin/bandwidth \
    /bin/cni \
    /bin/conntrack \
    /bin/containerd \
    /bin/containerd-shim-runc-v2 \
    /bin/ethtool \
    /bin/firewall \
    /bin/ip \
    /bin/ipset \
    /bin/k3s \
    /bin/losetup \
    /bin/pigz \
    /bin/runc \
    /bin/which \
    /bin/aux/xtables-legacy-multi \
/usr/bin/

RUN ln -s /usr/bin/cni /usr/bin/bridge && \
    ln -s /usr/bin/cni /usr/bin/flannel && \
    ln -s /usr/bin/cni /usr/bin/host-local && \
    ln -s /usr/bin/cni /usr/bin/loopback && \
    ln -s /usr/bin/cni /usr/bin/portmap && \
    ln -s /usr/bin/k3s /usr/bin/crictl && \
    ln -s /usr/bin/k3s /usr/bin/ctr && \
    ln -s /usr/bin/k3s /usr/bin/k3s-agent && \
    ln -s /usr/bin/k3s /usr/bin/k3s-etcd-snapshot && \
    ln -s /usr/bin/k3s /usr/bin/k3s-server && \
    ln -s /usr/bin/k3s /usr/bin/kubectl && \
    ln -s /usr/bin/pigz /usr/bin/unpigz && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables-save && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables-restore && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables-translate && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables-save && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables-restore && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables-translate

# --- Rancher content (mutable tag, last to maximize cache hits) ---
RUN mkdir -p /var/lib/rancher
COPY --from=rancher /var/lib/rancher /var/lib/rancher
COPY --from=rancher /run /run

RUN mkdir -p /usr/share/rancher
COPY --from=rancher /usr/share/rancher /usr/share/rancher

COPY --from=rancher \
    /usr/bin/rancher \
    /usr/bin/rancher-machine \
/usr/bin/

# --- Working directory setup ---
ENV HOME=/go/src/github.com/rancher/kontainer-driver-metadata
ENV GOPATH=/go
VOLUME /var/lib/rancher
VOLUME /var/lib/kubelet
WORKDIR /go/src/github.com/rancher/kontainer-driver-metadata

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
