ARG RANCHER_VERSION=v2.14-head

FROM rancher/rancher:$RANCHER_VERSION AS rancher

FROM registry.suse.com/bci/golang:1.25

# --- Tool installations (most expensive, no dependency on rancher content) ---
ARG TARGETARCH=amd64
ENV ARCH=${TARGETARCH}
ENV GOLANGCI_LINT=v1.64.8

RUN zypper -n install git docker vim less file curl wget jq awk ruby && rpm -e --nodeps --noscripts containerd
RUN go install golang.org/x/tools/cmd/goimports@latest
RUN if [[ "${ARCH}" == "amd64" ]]; then \
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s ${GOLANGCI_LINT}; \
        curl -sL https://github.com/rancher/wharfie/releases/download/v0.6.1/wharfie-amd64 -o /bin/wharfie && chmod +x /bin/wharfie; \
        curl -sL https://github.com/regclient/regclient/releases/download/v0.9.0/regsync-linux-amd64 -o /bin/regsync && chmod +x /bin/regsync; \
    fi

ENV YQ_VERSION=v4.41.1
RUN wget -q https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${ARCH}.tar.gz -O - | tar xz && mv yq_linux_${ARCH} /usr/bin/yq

# --- K3s binaries (pinned tag, stable cache key) ---
COPY --from=rancher/k3s:v1.34.1-k3s1 \
    /bin/blkid \
    /bin/bandwidth \
    /bin/cni \
    /bin/conntrack \
    /bin/containerd \
    /bin/containerd-shim-runc-v2 \
    /bin/ethtool \
    /bin/firewall \
    /bin/ip \
    /bin/ipset \
    /bin/k3s \
    /bin/losetup \
    /bin/pigz \
    /bin/runc \
    /bin/which \
    /bin/aux/xtables-legacy-multi \
/usr/bin/

RUN ln -s /usr/bin/cni /usr/bin/bridge && \
    ln -s /usr/bin/cni /usr/bin/flannel && \
    ln -s /usr/bin/cni /usr/bin/host-local && \
    ln -s /usr/bin/cni /usr/bin/loopback && \
    ln -s /usr/bin/cni /usr/bin/portmap && \
    ln -s /usr/bin/k3s /usr/bin/crictl && \
    ln -s /usr/bin/k3s /usr/bin/ctr && \
    ln -s /usr/bin/k3s /usr/bin/k3s-agent && \
    ln -s /usr/bin/k3s /usr/bin/k3s-etcd-snapshot && \
    ln -s /usr/bin/k3s /usr/bin/k3s-server && \
    ln -s /usr/bin/k3s /usr/bin/kubectl && \
    ln -s /usr/bin/pigz /usr/bin/unpigz && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables-save && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables-restore && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/iptables-translate && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables-save && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables-restore && \
    ln -s /usr/bin/xtables-legacy-multi /usr/bin/ip6tables-translate

# --- Rancher content (mutable tag, last to maximize cache hits) ---
RUN mkdir -p /var/lib/rancher
COPY --from=rancher /var/lib/rancher /var/lib/rancher
COPY --from=rancher /run /run

RUN mkdir -p /usr/share/rancher
COPY --from=rancher /usr/share/rancher /usr/share/rancher

COPY --from=rancher \
    /usr/bin/rancher \
    /usr/bin/rancher-machine \
/usr/bin/

# --- Working directory setup ---
ENV HOME=/go/src/github.com/rancher/kontainer-driver-metadata
ENV GOPATH=/go
VOLUME /var/lib/rancher
VOLUME /var/lib/kubelet
WORKDIR /go/src/github.com/rancher/kontainer-driver-metadata

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
