#!/bin/bash
set -e
set -x

REPO="https://api.github.com/repos/rancher/rke/actions/workflows/git-actions-go-generate.yml/dispatches"

case $DRONE_BRANCH in
  dev-v2.8|release-v2.8)
    ACTION_TARGET_BRANCH="release/v1.5"
    ;;
  *)
    echo "Not a valid branch, not dispatching event"
    exit 0
esac

echo "DRONE_BRANCH: $DRONE_BRANCH"
echo "DRONE_COMMIT_AUTHOR: $DRONE_COMMIT_AUTHOR"

echo "Dispatching to branch ${ACTION_TARGET_BRANCH}"

# send dispatch event to workflow
curl -XPOST -u "${PAT_USERNAME}:${PAT_TOKEN}" \
        -H "Accept: application/vnd.github.v3+json"  \
        -H "Content-Type: application/json" $REPO \
        --data '{"ref": "'"$ACTION_TARGET_BRANCH"'","inputs":{"source_author":"'"$DRONE_COMMIT_AUTHOR"'"}}'
