#!/bin/bash
set -e

cd $(dirname $0)/..


echo Running go mod tidy
go mod tidy

echo Running go mod verify
go mod verify

echo Running go test
go test ./rke/...

echo Running go generate
go generate

source ./scripts/version

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    exit 1
fi

echo Skipping release versions check, out of band versions were released after RKE v1.3.13
# python3 check-kdm-data.py release-v2.5 release-v2.6
