#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)

GIT_TAG=$(git tag -l --contains HEAD | head -n 1)
if [[ "$GITHUB_EVENT_NAME" = "push" && "$GITHUB_REF_TYPE" = "tag" ]]; then
  GIT_TAG=$GITHUB_REF_NAME
fi

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"
TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi