name: Provisioning tests

on:
  push:
    branches:
      - 'dev-v*'
      - 'release-v*'
  pull_request:
    branches:
      - 'dev-v*'
      - 'release-v*'

jobs:
  provisioning-test:
    permissions:
      contents: read
      id-token: write
    runs-on:
      - runs-on
      - spot=false
      - runner=4cpu-linux-x64
      - run-id=${{ github.run_id }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        dist: [rke2, k3s]
        k8s-minor: [33, 34, 35]
        test-regex: ["^Test_Provisioning_.*$", "^Test_Operation_SetA_.*$", "^Test_Operation_SetB_.*$"]
    env:
      # this is due to the dapper pod having a host-port on the registry-cache container
      # we can hit this registry from dapper OR the host docker if we use the docker IP
      REGISTRY: "172.17.0.2:5000"
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: "0"
      - name: testdata
        run: mkdir -p build/testdata
      - name: Install Dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > ./.dapper
          chmod +x ./.dapper
      - name: Configure Docker for cgroupfs/insecure-registry
        run: |
          echo '{"insecure-registries": ["172.17.0.2:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          sudo docker info
      - name: Retrieve Registry Endpoint
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry | STAGE_REGISTRY_ENDPOINT;
      - name: Provisioning Operations tests
        run: |
          ./.dapper provisioning-tests
        env:
          LAST_COMMUNITY_RANCHER: v2.13.3
          CATTLE_AGENT_IMAGE: rancher/rancher-agent:head
          V2PROV_TEST_DIST: ${{ matrix.dist }}
          V2PROV_TEST_RUN_REGEX: ${{ matrix.test-regex }}
          KDM_TEST_K8S_MINOR: ${{ matrix.k8s-minor }}
          PREV_COMMIT_PR_SHA: ${{ github.event.pull_request.base.sha }}
          PREV_COMMIT_PUSH_SHA: ${{ github.event.before }}
