name: Check diff new k8s version(s)
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  run-script-add-output-comment:
    name: Run diff script and add output as comment
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run diff script
      run: |
        bash show-diff-new-k8s-version.sh $GITHUB_REF_NAME > show-diff-new-k8s-version.sh.output
        output="$(cat show-diff-new-k8s-version.sh.output)"
        output="${output//$'\n'/\\n}"
        output="${output// / }"
        echo "::set-output name=run-bash-script::$output"
      id: run_script
    - uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = '${{ steps.run_script.outputs.run-bash-script }}'
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
