name: Main workflow

on:
  push:
    branches:
      - 'dev-v*'
      - 'release-v*'
  pull_request:
    branches:
      - 'dev-v*'
      - 'release-v*'

jobs:
  validate:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/v0.6.0/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
          chmod +x /usr/local/bin/dapper

      - name: Validate
        run: dapper ci

  mirror-images:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && startsWith(github.ref_name, 'release-v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/v0.6.0/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
          chmod +x /usr/local/bin/dapper
      - name: Retrieve Registy secrets from vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/registry-endpoint/credentials token | REGISTRY_ENDPOINT ;
            secret/data/github/repo/${{ github.repository }}/registry-username/credentials token | REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/registry-password/credentials token | REGISTRY_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/stage-registry/rancher/rke-extended-life/credentials endpoint |  STAGE_REGISTRY_ENDPOINT ;
            secret/data/github/repo/${{ github.repository }}/stage-registry/rancher/rke-extended-life/credentials username |  STAGE_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/stage-registry/rancher/rke-extended-life/credentials password |  STAGE_REGISTRY_PASSWORD ;
            secret/data/github/repo/${{ github.repository }}/prime-registry/rancher/rke-extended-life/credentials endpoint |  PRIME_REGISTRY_ENDPOINT ;
            secret/data/github/repo/${{ github.repository }}/prime-registry/rancher/rke-extended-life/credentials username |  PRIME_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/prime-registry/rancher/rke-extended-life/credentials password |  PRIME_REGISTRY_PASSWORD ;                      
      - name: Validate
        run: dapper mirror-images

  upload:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: validate
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Retrieve Google auth from vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/google-auth/rancher/credentials token | GOOGLE_AUTH ;
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GOOGLE_AUTH }}'
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: data/
          destination: releases.rancher.com/kontainer-driver-metadata/${{ github.ref_name }}
          parent: false
          predefinedAcl: publicRead
          process_gcloudignore: false
          headers: |-
            cache-control: public,no-cache,proxy-revalidate

  dispatch:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: upload
    if: github.event_name == 'push' && (github.ref_name == 'release-v2.11-rke-extended-life' || github.ref_name == 'dev-v2.11-rke-extended-life')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Retrieve token from vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/github-token/credentials token | PAT_TOKEN
      - name: Run dispatch
        run: |
          gh workflow run "Go Generate" --repo rancher/rke --ref release/v1.8 -F source_author=${{ github.actor }}
        env:
          GH_TOKEN: ${{ env.PAT_TOKEN }}
